# Configuración de Checkov para proyecto universitario
# Proyecto: DINEX Tracking Individual

# Directorios a escanear
directory:
  - ../../terraform

# Framework
framework:
  - terraform

# Formatos de salida
output:
  - junitxml
  - json

# Checks a omitir (justificados para ambiente de desarrollo universitario)
skip-check:
  # S3 Bucket checks - No usamos S3 en este proyecto
  - CKV_AWS_18   # S3 bucket logging
  - CKV_AWS_19   # S3 bucket encryption
  - CKV_AWS_21   # S3 bucket versioning
  - CKV_AWS_144  # S3 bucket replication

  # Lambda checks - Simplificado para proyecto universitario
  - CKV_AWS_116  # Lambda DLQ (Dead Letter Queue) - No crítico para desarrollo
  - CKV_AWS_117  # Lambda inside VPC - Aumenta complejidad innecesariamente
  - CKV_AWS_173  # Lambda environment encryption - AWS ya cifra por defecto

  # IAM checks - Roles básicos para proyecto académico
  - CKV_AWS_111  # IAM policy wildcards - Aceptable en desarrollo

  # DynamoDB checks - Configuración básica suficiente
  - CKV_AWS_28   # DynamoDB point in time recovery - Solo necesario en producción
  - CKV_AWS_119  # DynamoDB table encryption - Ya habilitado con default

# Nivel de severidad mínimo a reportar
min-severity: LOW

# Modo compacto (menos verbose)
compact: true

# No fallar el build por checks fallidos (modo informativo)
soft-fail: true
